### ISSUE TITLE
Error: spawn E2BIG when handling uploaded files

### ISSUE THREAD

**Issue by dawnerd** [architect/sandbox#109]
I have a simple function setup that accepts an uploaded file (that will later be moved to s3) but sandbox crashes with `Error: spawn E2BIG` right away.

```
[0] internal/child_process.js:366
[0]     throw errnoException(err, 'spawn');
[0]     ^
[0] 
[0] Error: spawn E2BIG
[0]     at ChildProcess.spawn (internal/child_process.js:366:11)
[0]     at spawn (child_process.js:551:9)
[0]     at spawnChild (/Users/troy/Projects/<snip>/node_modules/@architect/sandbox/src/invoke-lambda/spawn.js:12:15)
[0]     at done (/Users/troy/Projects/<snip>/node_modules/@architect/sandbox/src/invoke-lambda/run-in-node.js:12:7)
[0]     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
```

**Steps to reproduce**
1. Any post function, mine has literally nothing in it but the default code generated from init.
2. Post a file to the path

**Expected behavior**
Body data should contain the file contents

**Additional context**

Did some googlin' and there might need to be a change to how sandbox passes data: https://stackoverflow.com/a/44091211

**Comment by ryanblock** [comment]
How large is the payload in question?

Bear in mind there are limitations to API Gateway and Lambda payload sizes that are significantly smaller than what Sandbox can handle on most machines.

Optimal method for transiting files to S3 is to do so directly, fwiw!

**Comment by dawnerd** [comment]
Yeah, aware of the size limitations. The file us under 5mb which I believe should be fine?

**Comment by ryanblock** [comment]
Ok, please include platform version, node version, machine specs, and any other env specific info.

**Comment by dawnerd** [comment]
Added, and after looking at the direct s3 stuff, might just go that way. Last time I tried a direct to s3 browser upload it was more of a hack, looks like it might just be a cleaner way anyways.

**Comment by ryanblock** [comment]
Thanks. And exact file size, please? Also, any special node config going on on your machine? (I assume not but gotta ask.)

@brianleroux recently whipped up a direct-to-S3 uploader for Architect, it's a gnarly project, highly suggest basing off his work! https://github.com/architect-examples/arc-macro-upload

**Comment by dawnerd** [comment]
Filesize: 4403240

No special node stuff going on.

I'd share the file but you know, client work and all ;)

**Comment by ryanblock** [comment]
All good! Just need to have all this so I can repro. If you can create a reduced test case repo even better – but as our bug template says, your issue WILL be prioritized because you included repro steps! :)

**Comment by dawnerd** [comment]
I can set one up later tonight

**Comment by ryanblock** [comment]
No worries, I'll see what I can do in the mean time. A couple other bits that'll help:
- This being uploaded as multi-part form encoded, binary octet, or something else?
- Is this a simple POST, or something else?
- Is the file binary or text? (This can impact our req encoding.)

**Comment by dawnerd** [comment]
Oh yeah so the form looks like:

```html
<form action="/upload" method="post" enctype="multipart/form-data">
  <div>
    <input type="file" accept=".pdf,.zip" name="file">
  </div>
  <div>
    <label>Year <input type="number" name="year" min="2015" max="2030" value="2019"></label>
  </div>
  <div>
    <select name="type">
      <option selected>.pdf</option>
      <option>.zip</option>
    </select>
  </div>
  <div>
    <input type="submit" value="Upload">
  </div>
</form>
```
