### ISSUE TITLE
unable to start sandbox without aws credentials file in place

### ISSUE THREAD

**Issue by filmaj** [architect/sandbox#24]
If i rename my `~/.aws/credentials` file to something else, no matter what combination of various env vars I use (including omitting all the AWS env vars below), I cannot start sandbox, it blows up with:

```
➜ NODE_ENV=testing AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar AWS_REGION=us-west-1 AWS_PROFILE=default arc sandbox
         app ⌁ arctonic
      region ⌁ us-west-2
     profile ⌁ default
     version ⌁ Architect CLI 6.0.20
         cwd ⌁ /Users/maj/src/arcandtonic.technology

✓ Found Architect manifest, starting up
✓ Project files hydrated into functions
{ CredentialsError: Missing credentials in config
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.readFileSync (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/util.js:95:26)
    at IniLoader.parseFile (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:6:47)
    at IniLoader.loadFrom (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/shared-ini/ini-loader.js:56:30)
    at SharedIniFileCredentials.load (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:104:41)
    at SharedIniFileCredentials.coalesceRefresh (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/credentials.js:205:12)
    at SharedIniFileCredentials.refresh (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/credentials/shared_ini_file_credentials.js:185:10)
    at SharedIniFileCredentials.get (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/credentials.js:122:12)
    at getAsyncCredentials (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/config.js:361:24)
  message: 'Missing credentials in config',
  errno: -2,
  syscall: 'open',
  code: 'CredentialsError',
  path: '/Users/maj/.aws/credentials',
  time: 2019-08-03T15:39:32.828Z,
  originalError:
   { message: 'Could not load credentials from SharedIniFileCredentials',
     errno: -2,
     syscall: 'open',
     code: 'CredentialsError',
     path: '/Users/maj/.aws/credentials',
     time: 2019-08-03T15:39:32.828Z,
     originalError:
      { errno: -2,
        syscall: 'open',
        code: 'ENOENT',
        path: '/Users/maj/.aws/credentials',
        message:
         'ENOENT: no such file or directory, open \'/Users/maj/.aws/credentials\'' } } }
/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

Error: Unable to list Dynamo tables
    at Response._tables (/Users/maj/src/arcandtonic.technology/node_modules/@architect/sandbox/src/db/create-table/_create-table.js:20:13)
    at Request.<anonymous> (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/maj/src/arcandtonic.technology/node_modules/aws-sdk/lib/request.js:685:12)
```

Are credentials required for sandbox running? If no, can we smooth over the experience here for users? At a minimum document the env vars needed in the README to make it run without actual AWS creds in place?

**Comment by filmaj** [comment]
For context, I am hitting this when trying to run end-to-end browser tests against a sandbox instance running on Travis CI.

**Comment by filmaj** [comment]
What's more, with latest architect-cli (6.0.28) linked to latest sandbox master, I can't reproduce this error...

**Comment by filmaj** [comment]
OK, when I'm using non-`npm link`ed packages, I can repro this... wtf. Need to nail down repro steps, this is confusing.

**Comment by filmaj** [comment]
OK I think I have repro steps, although bizarre ones!

I have `"@architect/cli": "^6.0.28"` in the `dependencies` section of my `package.json`.

If I run `arc sandbox`, it blows up:

```
➜ arc sandbox
         app ⌁ arctonic
      region ⌁ us-west-2
     profile ⌁ default
     version ⌁ Architect CLI 6.0.28
         cwd ⌁ /Users/maj/src/arcandtonic.technology

{ CredentialsError: Missing credentials in config
```

If I run `npx sandbox`, everything is fine!

```
➜ npx sandbox
         app ⌁ arctonic
      region ⌁ us-west-2
     profile ⌁ default
     version ⌁ Sandbox 1.2.9
         cwd ⌁ /Users/maj/src/arcandtonic.technology

✓ Starting up without AWS credentials
✓ @tables created in local database
    get / ................................. get-index
   post /api/signup ....................... post-api-signup
   post /api/login ........................ post-api-login
   post /api/logout ....................... post-api-logout
   post /api/notes ........................ post-api-notes
    get /api/notes ........................ get-api-notes
   post /api/notes/:noteID/del ............ post-api-notes-000noteID-del
✓ Sandbox started in 1243ms

    http://localhost:3333
```

🤔

**Comment by filmaj** [comment]
Getting closer... `npx sandbox` invokes the sandbox via [its `src/cli/cli.js` module](https://github.com/architect/sandbox/blob/master/src/cli/index.js), whereas `arc sandbox` [invokes the sandbox via the programmatic sandbox API _passing in the `disableBanner` option_](https://github.com/architect/cli/blob/master/src/commands/sandbox/start.js#L13).

That `disableBanner` option seems to make all the difference, which is super surprising, and kind of frustrating.

Further digging into sandbox execution differences in these cases: when running `npx sandbox`, this conditional is triggered, whereas with `arc sandbox`, it is not: https://github.com/architect/sandbox/blob/master/src/db/_get-db-client.js#L25

**Comment by filmaj** [comment]
Breakdown of how the db client bootstraps itself in the two execution cases:

with `npx sandbox`:

```
missingProfile? false
missingaccesskey? true
missingkeyid? true
what is dynamo config? Config { credentials: null }
```

with `arc sandbox`:

```
missingProfile? false
missingaccesskey? true
missingkeyid? true
what is dynamo config? Config {
  credentials:
   SharedIniFileCredentials { ... }
```

So in the blowing-up case (`arc sandbox`), dynalite has some manner of shared credentials object defined in its config, whereas with `npx sandbox` it does not, so with `npx sandbox`, it sets a fake secret key and access key id as environment variables - whereas with `arc sandbox` it does not.

Then, by the time `db/_init` executes and starts creating tables defined in the `.arc` file, that's where things blow up (here: https://github.com/architect/sandbox/blob/master/src/db/_init.js#L76-L84).

**Comment by filmaj** [comment]
I logged out `process.env` before the failing all to `createTable` (which blows up invoking `dynamo.listTables`), and in the passing case, the secret key and key id are set to `xxx`. In the failing case, these env vars are not set.

**Comment by filmaj** [comment]
So there's something about the difference in setup, which doesn't seem to be based on the existence of the profile, secret key and key id env vars, that set up the AWS config object to be with credentials and without credentials in the two cases. That leads to sandbox setting the secret key and key id env vars, or not. And that is ultimately the difference in behaviour.

Argh frustrating but I'm getting closer.. need to dig into how the AWS SDK sets up its config object 😣

**Comment by filmaj** [comment]
I'm still trying to trace down how this happens.. lol, so frustrating. I think regardless of how that happens, inspecting the DynamoDB object's `config` for a `credentials` truthy property (as per this code https://github.com/architect/sandbox/blob/master/src/db/_get-db-client.js#L24) is not a good way to check if AWS is initialized with credentials or not, as `config.credentials` could be Initialized to the `SharedIniCredentials` class inside `aws-sdk`, which, seems to me, lazily-loads credentials and, if not present in the `~/.aws/credentials` file, will blow up.

A related note is the code as a whole in https://github.com/architect/sandbox/blob/master/src/db/_get-db-client.js - seems kinda, iuno, messy (no offense intended)? We potentially overwrite the same env vars twice? Why? Additionally, this seems to clash / duplicate the logic inside `banner.js` of `@architect/utils`.

**Comment by filmaj** [comment]
LOL OMG we do it to ourselves! I was trying to track down why the hell `aws-sdk` was setting the credentials to an empty instance of `SharedIniCredentials` - turns out `@architect/cli` forces that! Holy fuck! https://github.com/architect/cli/blob/master/src/before/01-ensure-creds.js#L42-L50

So basically the repro case is:

1. Delete / rename your `~/.aws/credentials` file
2. Either have `AWS_PROFILE` set in your env, or have your AWS profile set in your `.arc` file (this last one is the one that got me!)
3. Run `arc sandbox` vs. `npx sandbox` to see the difference.

Not sure where this issue should be filed, but this whole aws creds handling needs sorting out and cleaning up. I'm gonna use `npx sandbox` in my app for now to use `@architect/sandbox` directly instead of via the CLI.

**Comment by ryanblock** [comment]
Phil, thanks again for these repro steps. I'm digging into this (finally). Moving this to the utils repo.
